name: VulDe Security Linter

on:
  push:
    paths:
      - '**.py'

jobs:
  vuln-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.9

      - name: Clone my friend's repository
        run: |
          git clone --single-branch https://github.com/Keracles/VulnerabilityDetectionPackage.git

      - name: Pull models
        run: |
          wget https://p5qshw.db.files.1drv.com/y4mtWQF9heecoSfG9AypEg6ExBgh-dbLg14KguuLQmRc-9rd60XanP1uioiZ431Edu0CdryObt5WGXo2yMOsTe2FNuopc-p7ZNa3KYkWfswbgyRc7iyz898xy8MJBPttCWCgvrogCc9iigHpKY4xC2m5MNPxMPaPOUlgfDCTwaBseJU4i3FltV7gRPpn-Q2Emfw7cQIQ-MA_JP5iHcYm7-sfOAyfVGb1VkdIxSM336xeAk?AVOverride=1 -O models.zip
          unzip models.zip -d ./VulnerabilityDetectionPackage/vulde/vulde/models

      - name: Install VulDe package
        run: |
          cd ./VulnerabilityDetectionPackage/vulde
          pip install -e .

      - name: Run VulDe Linter on my file (test.py)
        run: |
          cd ./VulnerabilityDetectionPackage
          python analyseur.py ../test.py test --display-risk-level LOW --fail-on-risk-level HIGH
