name: VulDe Security Linter

on:
  push:
    paths:
      - '**.py'

jobs:
  vuln-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.9

      - name: Clone my friend's repository
        run: |
          git clone --single-branch https://github.com/Keracles/VulnerabilityDetectionPackage.git

      - name: Pull models
        run: |
          wget https://p5qshw.db.files.1drv.com/y4mIcJt5eiuUBdZKOXw9P4Pi7luxVeeK92hErkdwNapM-vGcThV7XcSlhTkfTkX_BR5RXtYA6AYAU5jC9Etuz7th-xuTAC5UguzZsYJM-pJZv6wiXEuKZ6UKvMwpTJXnwOhkS-muEId_XPdjCdgWVFze3ABomeQBeVaEuxR8civyvOhzXnzNByDPvXEdu9mdyZjH3qfddlf0_WRsZFIAIAZuhX3UAzzswvUUQkggoSiYX4?AVOverride=1 -O models.zip
          unzip -o models.zip -d ./VulnerabilityDetectionPackage/vulde/vulde/models

      - name: Install VulDe package
        run: |
          cd ./VulnerabilityDetectionPackage/vulde
          pip install -e .

      - name: Run VulDe Linter on my file (test.py)
        run: |
          cd ./VulnerabilityDetectionPackage
          python analyseur.py ../test.py test --display-risk-level LOW --fail-on-risk-level HIGH
